### ISSUE TITLE
"s" has no change in XS 

### ISSUE THREAD

**Issue by tylerhartwig** [nosami/XSVim#11]
Pressing "s" in normal mode in Xamarin Studio does not delete the current character and move to insert mode. I did a quick check through the source code and saw that it should do this.

Xamarin Studio 6.3 (build 863)
Vim (XSVim that is) Version 0.13

Let me know if there is more helpful information I can provide, I'm just glad were getting a well-functioning Vim on Xamarin Studio/VS4Mac

**Comment by tylerhartwig** [comment]
After checking again, I assume the support hasn't been updated to the XS Gallery. Sorry for the new issue.

**Comment by nosami** [comment]
Yeah... there have been problems with the XS addin build server. I'll probably add my own feed some time soon and publish there.

**Comment by nosami** [comment]
You should be able to install 0.14 from here https://github.com/nosami/XSVim/releases/download/0.14/XSVim.XSVim_0.14.mpack

**Comment by tylerhartwig** [comment]
Awesome, thanks, I assume eventually XS will get updates too?

**Comment by nosami** [comment]
It should automatically end up in the XS feed in theory whenever I push to master, but in practice, the addin build server has been very temperamental... no new addins since 04/15 http://addins.monodevelop.com/

When I have some free time, I'll add my own feed that you can add to XS to get automatic updates from.

**Comment by tylerhartwig** [comment]
Gotcha, I guess the real one to worry about is VS for Mac, thanks for the great plugin though, been needing a real Vim plugin for XS for a while now.
