### ISSUE TITLE
Save character position when moving up/down

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#12]
When using `j` to move down a file, the cursor should always aim to be at the same character position it was when you started moving down.

Currently, if the cursor moves left while moving down (i.e. the next line was too short), if you move down to a longer line it won't try to make its way back.

**Comment by nosami** [comment]
Yeah... I noticed this too. Will try and fix.

**Comment by nosami** [comment]
Fixed by https://github.com/nosami/XSVim/commit/4be048b735a15982571baf58b3fd1991162e61a2
