### ISSUE TITLE
Paste doesn't preserve newlines (when line endings are `\r\n`)

### ISSUE THREAD

**Issue by qguv** [nosami/XSVim#121]
After copying a line with `yy`, `pp` should insert the default register's contents on a new line. Right now, it appends to the current line.

**Comment by nosami** [comment]
Which version are you on?

I just tried this and can't see any issues with it... and there are some tests here https://github.com/nosami/XSVim/blob/7.0/XSVim.Tests/YankAndPut.fs#L52-L58

Is it not working anywhere in any file, or just in certain places?

**Comment by qguv** [comment]
Here's a little demo. After the paste, my cursor gets thrown way down in the file, so I have to use repeated 'k' to get it back. The 'R' keypresses are actually 'P' keypresses; that's a bug in the on-screen keypress displayer.

<img src="https://ptpb.pw/2OXE.gif" />

**Comment by nosami** [comment]
Are you using 0.34.0? it looks like an old bug.

**Comment by qguv** [comment]
This is on 0.34.0.

**Comment by nosami** [comment]
Oh ... I see what the issue is now.... it happens when you have `\r\n` line endings. Will get this fixed

**Comment by nosami** [comment]
Fixed this along with some other `\r\n` issues. 

Please let me know if you find any other issues, I very rarely use Windows line endings. Thanks!

**Comment by nosami** [comment]
Seems I didn't fix this very well at all. Re-opening

**Comment by nosami** [comment]
Ok... should be good now!

**Comment by qguv** [comment]
Confirmed fixed, thanks. Nice work!

**Comment by nosami** [comment]
@qguv Thanks for confirming. Each test is now ran twice - once with LF line endings, and then again with CRLF line endings, so hopefully this will be enough to catch this sort of issue in the future. Cheers!
