### ISSUE TITLE
Implement double-backtick movement command

### ISSUE THREAD

**Issue by qguv** [nosami/XSVim#122]
Double backtick should take the user to the last location in the file. Right now it does not.

**Comment by nosami** [comment]
This sounds pretty useful - I'll look into it.

You can use `. to jump to the last edit at the moment.

**Comment by nosami** [comment]
If I understood how this was supposed to work, I would implement it :)

**Comment by nosami** [comment]
So it seems that `G, gg, H, M, L, /, {, }, <C-f>, <C-d>, <C-b>, <C-f>` are jump commands. 

Any time that you jump within the same file, `` should take you back to the line and column of the location before the jump and '' should take you to the line of the jump.

I'm not familiar with this command.. Am I missing anything else that might be considered a jump?

**Comment by qguv** [comment]
Hi again! It looks like double-backtick wasn't implemented in 0d4628d8cbb0096717af063967548383edb416d1. I tested all the jump commands I use against their intended function per their `:h` page.

These are perfect:

- [X] `G` jump to last line
- [X] `gg` jump to line 1
- [X] `{` jump to the previous blank line
- [X] `}` jump to the next blank line
- [X] `^D` move down
- [X] `^F` move down more
- [X] `^U` move up
- [X] `^B` move up more

These go a little too far, causing a scroll where they shouldn't:

- [ ] `H` jump to top of screen without scrolling
- [ ] `M` jump to middle of screen
- [ ] `L` jump to bottom of screen

These don't seem to be implemented yet:

- [ ] `^E` move the screen a line down without moving cursor (not implemented)
- [ ] `^Y` move the screen a line up without moving cursor (not implemented)
- [ ] <code>\`\`</code> return cursor to last position before jumping (not implemented)

Cheers!

**Comment by nosami** [comment]
> It looks like double-backtick wasn't implemented in 0d4628d

That's strange. It's working fine for me.

> These go a little too far, causing a scroll where they shouldn't:

Yeah, I know about this, but not sure that there is anything I can do about it. I get the visible lines [here](https://github.com/nosami/XSVim/blob/0d4628d8cbb0096717af063967548383edb416d1/XSVim/XSVim.fs#L224). The `?` indicates that I'm using reflection here to access this property, it's not even intended to be used by addin authors :(

> These don't seem to be implemented yet:
 ^E move the screen a line down without moving cursor (not implemented)
 ^Ymove the screen a line up without moving cursor (not implemented)

^Y works for me, but ^E doesn't. I'm not really sure why yet. There should be no difference between the two https://github.com/nosami/XSVim/blob/0d4628d8cbb0096717af063967548383edb416d1/XSVim/XSVim.fs#L1210-L1211. I need to look into it.
