### ISSUE TITLE
Modify "LastLine" command to support "GoToLine"

### ISSUE THREAD

**Issue by aguywithcode** [nosami/XSVim#13]
In Vim The G command can be modified with a number to GoTo a specific line number.

This is also supposed to work with ##gg 

http://vim.wikia.com/wiki/Go_to_line

Also double digit numbers followed by a command don't work. For instance 9j takes you down 9 lines 10j takes you down one line
12j takes you down two.

**Comment by nosami** [comment]
Thanks, will get this fixed!

**Comment by aguywithcode** [comment]
Okay I was trying to see where it was happening so I could submit a patch but I couldn't find it.

Sent from my iPhone

On May 1, 2017, at 12:32 AM, Jason Imison <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, will get this fixed!

**Comment by nosami** [comment]
No worries - it wasn't obvious at all!

**Comment by nosami** [comment]
Fixed by #14. Thanks!

**Comment by nosami** [comment]
Just released 0.16 containing this fix here for VS for Mac https://github.com/nosami/XSVim/releases/tag/0.16

**Comment by aguywithcode** [comment]
Works great in VS for Mac GA

**Comment by nosami** [comment]
There have been quite a few more releases since 0.16. You might want to look for the latest one :) https://github.com/nosami/XSVim/releases
