### ISSUE TITLE
% does not count parentheses properly

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#158]
This example fails `(foo(bar))` when you use `%` at the last closing `)`. It jumps to opening `(` before `bar`.

**Comment by nosami** [comment]
Please try v0.40.6. Seems to be working to me, although I couldn't make the test work for the exact case you describe.

**Comment by hifi** [comment]
Now it does work, thanks!

**Comment by nosami** [comment]
Thanks for confirming!
