### ISSUE TITLE
r<ENTER> does not work

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#159]
For some reason in my work flow I use `r<ENTER>` quite often to replace a character by a new line. It does nothing currently.

**Comment by nosami** [comment]
Hey @hifi!! 

Fixed this in 0.40.5, thanks for reporting

**Comment by hifi** [comment]
Thanks! Most things I use seem to work fine now so it's very usable.

**Comment by nosami** [comment]
@hifi: That's good to hear!
