### ISSUE TITLE
`w` should not ever land you after the last character of a line

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#16]
If you are on any line other than the last line of a document, `w` will eventually bring you to the character location after the end of the line.

(Where `#` is the cursor)
```
#esting
Okay
```
Tap `w`
```
Testing#
Okay
```

**Comment by richkzad** [comment]
Expected behavior in the above case would be:

```
#esting
Okay
```
Tap `w`
```
Testing
#kay
```

**Comment by nosami** [comment]
Fixed in 0.16.4
