### ISSUE TITLE
Crash when trying to open a file in latest stable Visual Studio for Mac

### ISSUE THREAD

**Issue by dlprows** [nosami/XSVim#162]
After updating to the latest stable Visual Studio for mac i get a type load error whenever i try to open a file.

Error:

> Could not load type of field 'ICSharpCode.PackageManagement.Scripting.PackageManagementConsoleHost:sourceRepositoryProvider' (4) due to: Could not load file or assembly 'NuGet.Protocol.Core.Types, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:NuGet.Protocol.Core.Types, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:<none>

My about Visual Studio shows the following

> Visual Studio Community 2017 for Mac
> Version 7.1 (build 1297)
> Installation UUID: 6a4c8b85-e6a1-4ddf-a70b-39391658e57c
> Runtime:
> 	Mono 5.2.0.215 (d15-3/da80840) (64-bit)
> 	GTK+ 2.24.23 (Raleigh theme)
> 
> 	Package version: 502000215
> 
> NuGet
> Version: 4.3.0.2418
> 
> .NET Core
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	2.0.0
> 	1.1.1
> 	1.0.4
> SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
> SDK Versions:
> 	2.0.0
> 	1.0.1
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks
> 
> Xamarin.Profiler
> Version: 1.5.5
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Xamarin.Android
> Version: 7.4.0.21 (Visual Studio Community)
> Android SDK: /Users/i51047/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		2.3   (API level 10)
> 		4.0.3 (API level 15)
> 		4.3   (API level 18)
> 		4.4   (API level 19)
> 		5.0   (API level 21)
> 		5.1   (API level 22)
> 		6.0   (API level 23)
> 		7.0   (API level 24)
> 
> SDK Tools Version: 26.0.2
> SDK Platform Tools Version: 25.0.6
> SDK Build Tools Version: 23.0.2
> 
> Java SDK: /usr
> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
> 
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Xamarin Inspector
> Version: 1.2.2
> Hash: b71b035
> Branch: d15-1
> Build date: Fri, 21 Apr 2017 17:57:12 GMT
> 
> Apple Developer Tools
> Xcode 8.3.3 (12175.1)
> Build 8E3004b
> 
> Xamarin.iOS
> Version: 10.12.0.20 (Visual Studio Community)
> Hash: 80b8487d
> Branch: d15-3
> Build date: 2017-08-18 16:07:26-0400
> 
> Xamarin.Mac
> Version: 3.6.0.19 (Visual Studio Community)
> 
> Build Information
> Release ID: 701001297
> Git revision: 9c5299666538b2f8baf501418a5c064d784d64da
> Build date: 2017-08-07 11:29:35-04
> Xamarin addins: 3bb0c32a14f1b7e368bf5ac53a84c3581c019391
> Build lane: monodevelop-lion-d15-3
> 
> Operating System
> Mac OS X 10.12.5
> Darwin 16.6.0 Darwin Kernel Version 16.6.0
>     Fri Apr 14 16:21:16 PDT 2017
>     root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
> 
> Enabled user installed addins
> AddinMaker 1.3.7
> NuGet Package Explorer 0.2
> NuGet Package Management Extensions 0.12.2
> Vim 0.42.0
> Manifest.addin 0.0.0.0
> 

If I disable the vim plugin, the error goes away, which leads me to believe that its the vim plugin

**Comment by nosami** [comment]
Hmm, ok. I can't imagine how the vim addin could be interfering here though.

**Comment by dlprows** [comment]
I did some fiddling around, and it looks like its a problem with having both Nuget Package Management Extensions and Vim enabled at the same time.
I'm fine with just disabling the nuget extensions so that I can use Vim.

Thanks for letting me know that you didn't think it was vim. Since it would only crash when i tried opening a file, and disabling the vim addin made the crash go away, i didn't do quite as much testing as i should have.
