### ISSUE TITLE
Indentation and cursor position are wrong after r<ENTER>

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#163]
The cursor is left at the end of the line where it should instead be on the first character of the new line.

Also the new line is not indented properly like if you would do `xi<ENTER>` which works like it should.

**Comment by nosami** [comment]
Ok. Will fix this. I should have checked `r<enter>` in Vim first, I never use it.

**Comment by nosami** [comment]
When I try this in vanilla vim, with no language plugins, then the cursor is on a new line, but not indented.

I guess XSVim should be a little cleverer here and always auto-indent (maybe based on the VS for Mac indentation setting). There are probably more cases of auto-indent not working that I haven't considered.

**Comment by hifi** [comment]
True, without any knowledge of indentation rules Vim does not indent the new line but the cursor does move there.

These things were "working" (but not this particular case) in JustEnoughVi because it abused the IDE indentation rules by adding a new line like the user would which would then invoke the text editor to do its own indenting rather than the plugin trying to figure it out.

Although, `o` indents properly so it's already doing that I suppose and the same thing could be done for this.

**Comment by nosami** [comment]
Yeah, I'm going to try and do the same thing here (insert enter via base.KeyPress instead of "\n") and check all the other cases (`O, o, I, i, C, cc, s, S`) etc.

**Comment by nosami** [comment]
@hifi btw, your presence would be greatly appreciated in the gitter room. Your feedback is invaluable :)

**Comment by nosami** [comment]
Fixed in 0.42.3
