### ISSUE TITLE
> and < should wait for a second character

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#165]
The single line indentation commands are `<<` and `>>` but XSVim indents with only `<` and `>`. In visual select mode plain `>` and `<` are correct, though.

They seem to accept directional keys `jk` in Vim to indent current and a line above or below at the same time.

**Comment by nosami** [comment]
OK. Will check this out. Thanks!

**Comment by nosami** [comment]
> They seem to accept directional keys jk in Vim to indent current and a line above or below at the same time.

Wow... had no idea

**Comment by hifi** [comment]
> Wow... had no idea

Neither did I. If I need to do that I always use visual select.

**Comment by nosami** [comment]
`>>` is now used (0.42.1) to indent when in normal mode. Will need to give some thought on how to handle `>j` or `>3j`, `>}` etc. My gut feeling is that some sort of indentation sub mode would be needed.

**Comment by nosami** [comment]
All of your issues are fixed in 0.43.0 (see https://github.com/nosami/XSVim/blob/ca719a7ddfdd75963609ec9e804807c4ed483ebe/XSVim.Tests/IndentationTests.fs). Some indentation issues remain though. Merged anyway as there are a number of improvements here.
