### ISSUE TITLE
CTRL+D Doesn't scroll page. It deletes the word/line instead

### ISSUE THREAD

**Issue by HelloKashif** [nosami/XSVim#171]

**Comment by hifi** [comment]
You need to unbind the keys you want XSVim to capture from Xamarin Studio.

**Comment by nosami** [comment]
Actually, unbinding keys should not be necessary any more. You should just need to install the latest version from the [releases](https://github.com/nosami/XSVim/releases) page

Control-D is automatically unbound https://github.com/nosami/XSVim/blob/7.0/XSVim/XSVim.fs#L29
