### ISSUE TITLE
In replace mode, `u` works differently from Ctrl-Z

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#177]
Trying out replace mode, if I replace a bunch of text within a line and then hit `u` only the last character is reverted. In Vim and by using the MonoDevelop Ctrl-Z shortcut all of the text that was typed will be reverted or at least a larger chunk.

I would expect `u` to do the same thing as the IDE undo command.

**Comment by nosami** [comment]
Will get this fixed - thanks. `u` should delete everything that was entered whilst in replace mode.
