### ISSUE TITLE
`x` on second last character in line incorrectly moves cursor

### ISSUE THREAD

**Issue by hifi** [nosami/XSVim#179]
Consider `foo(ba$r)`

Hitting `x` should end up with:

`foo(ba$)`

But the cursor is currently incorrectly moved (wrong order of evaluation?):

`foo(b$a)`

**Comment by nosami** [comment]
Which version are you running on? It's not doing that here.

![foobar](https://user-images.githubusercontent.com/667194/30519828-a5f9d924-9b97-11e7-97ad-246424a7c51a.gif)

**Comment by hifi** [comment]
Apparently I got confused between my work and home MD installs, I had a really old one at home. No problem with latest, sorry.

**Comment by nosami** [comment]
No worries - thanks!
