### ISSUE TITLE
Keyboard shortcuts like ⌘S should be ignored by vim plugin

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#18]
When a file has changed since its saved version, `⌘s` will correctly save the file.

However, if the file has already been saved, `⌘s` will be interpreted by vim as `s`, which deletes the character you're on and brings you to insert mode.

I think that if a keyboard shortcut is assigned in VS but is currently not available, the keyboard shortcut should do absolutely nothing, and not be passed on to the vim extension.

**Comment by richkzad** [comment]
Maybe it should be: any time a key is hit along with ⌘, it should be ignored by the vim extension?

**Comment by nosami** [comment]
Ok... I just ignore the cmd key, it's easier :)
