### ISSUE TITLE
Bug: Can't quit Visual Studio with Vim plugin

### ISSUE THREAD

**Issue by CallumHoward** [nosami/XSVim#190]
Hi,

This is not my thread, but I have been able to replicate the bug described on the latest release with latest Visual Studio Mac and latest Unity.

https://developercommunity.visualstudio.com/solutions/104684/view.html 

As described, when quitting, a blank Visual Studio window remains open and must be force quit. Happy to provide further debug info if required. It does not occur if Visual Studio was not launched from Unity.

To replicate: 
- Create a script in Unity with the editor set in preferences as Visual Studio (Mac). 
- Double click on the script to edit. 
- Quit Visual Studio.

**Comment by nosami** [comment]
Will investigate, thanks!

**Comment by nosami** [comment]
I believe I already fixed this issue in monodevelop itself [here](https://github.com/mono/monodevelop/commit/c0bd526054d4bc453a2f769c6d1db48a1b587490#diff-710fa148d4e36578d081214888b78fe6) but the fix probably hasn't been rolled out yet.

Please can you try opening the Error List pad before you quit and let me know if that helps?

**Comment by CallumHoward** [comment]
I am not sure why, but I can no longer replicate the issue. Nothing shows in the Error List pad, and when I use CMD-Q, it quits fully. Happy to close for now and I'll update if it reoccurs.

**Comment by nosami** [comment]
Looks like 7.4.0.884 went into the Beta channel on 25th Jan. Maybe you have that? It contains my fix.
