### ISSUE TITLE
How to enable Substitute Command mode?

### ISSUE THREAD

**Issue by weijia-yu** [nosami/XSVim#191]
I tried to use :s/oldword/newword by selecting lines in normal mode, but nothing happened. What is the correct way to do it in XSVim?

**Comment by nosami** [comment]
That isn't supported yet. I'll try and add it soon.

You can use Alt+Command+F for now.

**Comment by marcinbiegun** [comment]
Would love to see this implemented.

**Comment by nosami** [comment]
OK. I added this to 0.61.0

It works for the common cases of replacing within a selection `:'<,'>s` and within the whole document `:%s`

There are some limitations as it relies on VSMac intrinsics currently, but it's working well enough for my use cases :)
