### ISSUE TITLE
Undo button undo all the lines

### ISSUE THREAD

**Issue by weijia-yu** [nosami/XSVim#192]
When I press command+z to undo, it will undo all my changes since last save, sometimes i cannot redo and my changes are gone. Shouldnt it just undo my last certain line change?

**Comment by nosami** [comment]
It should undo every change that you made while you were in Insert mode like Vim. Is that not what it is doing? Do you have a repro?

**Comment by weijia-yu** [comment]
I guess I haven't been gotten used to vim mode undo yet, thanks for explaining

**Comment by nosami** [comment]
Great, thanks! :)
