### ISSUE TITLE
Some commands with shift not working

### ISSUE THREAD

**Issue by priort** [nosami/XSVim#2]
Hi there, thanks for creating this plugin.
I am just have a problem using xamarin studio 6.5 on mac
When I try to move up and down in blocks with
shift { 
shift }

it doesn't work,
or if I select an opening with v and try to navigate to the closing paren with 
shift % )
it doesn't work.

or another example, if I am within parens and try to select everything within the parens, 
if I use the combination
v 
i
shift )

nothing happens either.

Is there some setting that I need to change to make the shift key work properly with XSVim?

Thanks a million

**Comment by nosami** [comment]
I haven't got around to implementing `{` and `}` yet or `v%(`

`vi)` should work. Looks like a regression.

Leave it with me.

**Comment by priort** [comment]
Hi Jason,
Thanks a million. I really like the plugin by the way. It definitely enhances my experience with Xamarin studio.

Tom

**Comment by nosami** [comment]
I didn't realise that `%` worked without being on a brace character to begin with. Learnt something new :)

**Comment by priort** [comment]
Thanks for the update. Just wondering how can I build the mpack from source so that I can add from file in Xamarin studio?

**Comment by nosami** [comment]
There is a bug with the addin build server - [no new releases](http://addins.monodevelop.com/) since 24th Jan. It should have automatically appeared in the feed.

I can't remember how to create mpack files off the top of my head, but if you give me a few minutes, I'll create one and attach it to the Releases tab on here.

**Comment by nosami** [comment]
Take a look here https://github.com/nosami/XSVim/releases/tag/0.13 . Please let me know if it works for you!

**Comment by priort** [comment]
That worked! My xamarin studio closed just at the end of the installation
but, once I started up Xamarin studio, it was installed.

The new additions are great. Its lovely having the { and } working to jump
up and down through my code. Hardly ever need to touch the mouse now :)
and vi ) is so convenient too!

Thanks so much
Tom

**Comment by nosami** [comment]
Great!
