### ISSUE TITLE
"s" doesn't work in visual mode

### ISSUE THREAD

**Issue by paulopicasso** [nosami/XSVim#203]
Maybe I'm missing something and I know I can achieve pretty much the same thing using "c" but I'm quite used to replacing selected text in visual mode using "s" key.

**Comment by nosami** [comment]
No, you're not missing anything. It's just never been implemented :) I always use 'c' for this.

I'll add it now.

**Comment by nosami** [comment]
Fixed in 0.49.3. It will appear on the releases page soon, and in the official addin feed shortly afterwards.

**Comment by paulopicasso** [comment]
Thank you very much!

**Comment by nosami** [comment]
No problem - thanks for reporting it!
