### ISSUE TITLE
can't install plugin version 0.49.6

### ISSUE THREAD

**Issue by ghost** [nosami/XSVim#205]
Trying to install 0.49.6 and it goes through installer and then fails at the end.  Version information is here:

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4.1 (build 48)
Installation UUID: e557e40d-f4ba-498c-bf3b-457a6d6a4e84
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.0-preview2-1-003177
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/lebeaaa/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.8.1.28 (Visual Studio Enterprise)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

ProjectTemplateXamarin 2018.1.221
Internet of Things (IoT) development (Preview) 7.1

**Comment by nosami** [comment]
Have you installed a previous version successfully before? Have you tried installing the mpack file manually from the [Releases page](https://github.com/nosami/XSVim/releases)?

**Comment by ghost** [comment]
Installing manually works.

Aaron via mobile

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nosami** [comment]
There shouldn't really be any difference between the 2 methods. No idea what went wrong there.

If you post your IDE logs from the time of the crash (Help -> Open Log Directory) there might be some clue as to what went wrong.

**Comment by nosami** [comment]
Please can you see if version 50.1 from the feed works for you?

**Comment by nosami** [comment]
I'm going to assume this is the same issue as #206. Please re-open if you have any more issues. Thanks!
