### ISSUE TITLE
Character toggled with "~" (i.e. case toggle command) does not appear to change upon toggling.

### ISSUE THREAD

**Issue by ASC95** [nosami/XSVim#210]
I'm on a 2014 MacBook Air running Visual Studio Community with the .NET Core.

When I toggle the case of a character with "~", the character DOES change case, but the character still displays as its original case. 

For example, if I toggle the first "a" character in "consoleapplication" to be "consoleApplication", the word still displays as "consoleapplication" even though the "a" became "A". The character displays incorrectly until I enter visual mode, at which point the word correctly displays as "consoleApplication".

When the cursor blinks on the letter which had its case toggled, the letter appears to alternate between its lowercase and uppercase as the cursor blinks on and off.

**Comment by nosami** [comment]
![tildevs](https://user-images.githubusercontent.com/667194/38793840-bd201880-414a-11e8-9b70-7716fec3a6ce.gif)

This is what I see.

**Comment by nosami** [comment]
Which version of VS Community are you using? It's possible that it's an issue that's been fixed there. Thanks.

**Comment by ASC95** [comment]
Problem is resolved in newest update.
