### ISSUE TITLE
Entering insert mode causes vim to enter overtype (replacement) mode after renaming a file

### ISSUE THREAD

**Issue by ASC95** [nosami/XSVim#211]
I'm running Visual Studio Community 7.4.3 on a 2014 MacBook Air.

When I first start Visual Studio, everything works fine.

However, if I rename a file and then immediately resume editing it, insert mode no longer works at all. When I enter insert mode (via "i", "I", "a", etc.) vim goes into replacement mode instead so that everything is overwritten as I type.

If I restart Visual Studio, everything is fine.
If I rename a file, close it, then reopen it, everything is fine.

**Comment by nosami** [comment]
Can confirm - will get this fixed. Thanks for reporting!

**Comment by nosami** [comment]
Fixed in 0.53.1
