### ISSUE TITLE
'x' deletes past end of line

### ISSUE THREAD

**Issue by mweber26** [nosami/XSVim#212]
`x.Get("active", f^alse));`

With caret between the f and a if you hit 20x it should stop at the end of the line, but it either goes on to other lines or starts deleting before the f:

`x.Ge`

**Comment by nosami** [comment]
Can confirm. Will get this fixed - thanks!

**Comment by nosami** [comment]
Fixed in 0.54.2

**Comment by mweber26** [comment]
I don't think this is quite right still.
`Do^Download();`
then hit 500x
And it deletes `Download()` but not the ;

**Comment by nosami** [comment]
Eek - sorry about that! Let me have another look

**Comment by nosami** [comment]
Fixed in 0.54.4

Not really happy with my fix, but it works now at least

**Comment by nosami** [comment]
p.s. `D` works better for this :)

**Comment by mweber26** [comment]
There's always a better command, but 25 years of vi is hard to adjust :)

**Comment by mweber26** [comment]
I'm not sure if you want this in the same issue, but 500x at the end of the line does not set up the copy/paste buffer like D does.

`if(_item^s == null)` **500x** **p**  === `if(_item)^`
where as
`if(_item^s == null)` **D** **p** === `if(_items == null)^`

**Comment by nosami** [comment]
I don't believe I ever used x with a multiplier - I had no idea it did that. I guess that's a different issue. I'll file it.
