### ISSUE TITLE
'A' then dot with backspace

### ISSUE THREAD

**Issue by mweber26** [nosami/XSVim#214]
Go to a line then hit **A** to insert at the end of the line, then type something, but use backspace to correct yourself, then escape.

Then go to the next line and hit **dot**, this should insert the corrected text.

https://imgur.com/a/qpCkjVj

**Comment by mweber26** [comment]
Somehow this looks like it actually inserts the backspace characters with the **dot**.  The line you do the dot on acts very strange at the end of the line with characters appearing and disappearing.

**Comment by nosami** [comment]
Fixed in 0.54.5 - thanks!
