### ISSUE TITLE
'd' + 'j'and 'd' + 'k' combinations are not working like vanilla VIM key bindings.

### ISSUE THREAD

**Issue by djnsu** [nosami/XSVim#227]
I think 'd' + 'j' and 'd' + 'k' key combinations should work like the original VIM and delete one row under cursor and another row in direction of deleting.

**Comment by nosami** [comment]
Hi @djnsu! You are right. I don't use these bindings myself but thought they worked. I'll get this fixed.

**Comment by nosami** [comment]
`d2j` etc. needs to work too

**Comment by nosami** [comment]
Fixed in 0.60.3. Thanks for reporting!
