### ISSUE TITLE
Cannot install: dependency conflicts

### ISSUE THREAD

**Issue by CalebMacdonaldBlack** [nosami/XSVim#228]
I have a fresh install of visual studio that I installed with `brew cask install visual-studio`

<img width="886" alt="screen shot 2018-06-11 at 9 21 31 pm" src="https://user-images.githubusercontent.com/5868450/41228934-814e6290-6dbd-11e8-93cd-5a9532b0fa36.png">

**Comment by nosami** [comment]
What version of Visual Studio is it (go to `Visual Studio -> About`) ?

Maybe you need to use an older version of XSVim that targets 7.4.

**Comment by nosami** [comment]
`brew cask cat visual-studio` shows that it is installing VS 7.5.2.40 for me at least. 

Please can you install XSVim from [here](https://github.com/nosami/XSVim/releases/download/0.60.1/XSVim.XSVim_0.60.1.mpack)

I think I messed something up while packaging here, but installing the file from the link above should work fine.

You can use this button to install from an mpack file
![image](https://user-images.githubusercontent.com/667194/41238789-b897d274-6d8e-11e8-8bfe-ea3e348c51b6.png)

**Comment by nosami** [comment]
Fixed in 0.60.5 Thanks for reporting!

**Comment by CalebMacdonaldBlack** [comment]
@nosami Thank you for the really quick fix! The manual install with that file works
