### ISSUE TITLE
Pressing `i` and then `Esc` at start of a line (or on an empty line) moves the cursor up to the end of the previous line

### ISSUE THREAD

**Issue by kibiz0r** [nosami/XSVim#230]
Note that `i` then `Esc` should still move the cursor back by one character when it's not at the start of the line.

**Comment by nosami** [comment]
![insert-escape](https://user-images.githubusercontent.com/667194/41372319-dda803d8-6f44-11e8-8b4b-ab0c76934ec4.gif)

It's not doing that for me. Which version of VSMac / XSVim are you using?

**Comment by nosami** [comment]
Never mind - I see what you mean now. Looks like a recent bug. The cursor should move backwards when it's not at the start of the line.

I'll get it fixed

**Comment by nosami** [comment]
I tried the most recent build with VS 7.6 and this is what I see. A different bug than the first gif :)

![insert-escape](https://user-images.githubusercontent.com/667194/41374100-29910b14-6f4a-11e8-8bd4-3d162194f3fa.gif)

**Comment by nosami** [comment]
Fixed in 0.60.6 - thanks for reporting!
