### ISSUE TITLE
Disable the use of System clipboard as the vim clipboard register

### ISSUE THREAD

**Issue by Blackvz** [nosami/XSVim#245]
Is there a way to disable the vim clipboard? Like I don't want to copy if I press "dd" to delete a line.

**Comment by nosami** [comment]
@Blackvz No, but I should be able to add this functionality if it's important to you.

**Comment by Blackvz** [comment]
I would love that :)

**Comment by nosami** [comment]
I guess you still want to save the value to a vim register so that you can use 'p' to put etc?

But not use the system clipboard for this?

**Comment by Blackvz** [comment]
Yep, that's exactly what I want

Thanks for your effort by the way! I'm really looking forward to this

**Comment by nosami** [comment]
This feature won't make it into XSVim. However, it works already in the VsVim port https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555
