### ISSUE TITLE
Asterisk (*) should start a new search

### ISSUE THREAD

**Issue by bmatzelle** [nosami/XSVim#254]
The asterisk (*) support added as part of [this ticket](https://github.com/nosami/XSVim/issues/38) does not simulate Vim behavior.  Hitting the * key should start a [typical (/) search](https://www.cs.swarthmore.edu/oldhelp/vim/searching.html).  What it is doing now is just moving the cursor to the next matching word under the cursor.  So it should do the following:

* Start a new search (clearing the previous search in the process) for the word located under the cursor.
* Enable the use of the "n" and "N" keys to move forward and backward, respectively.

**Comment by bmatzelle** [comment]
I am running Visual Studio on macOS Mojave with Vim 0.65.0.80.

**Comment by nosami** [comment]
Well. I just learnt something new today :)

**Comment by bmatzelle** [comment]
Great.  Let me know if I can be of further assistance.

**Comment by nosami** [comment]
Fixed in 0.65.2

**Comment by bmatzelle** [comment]
It works!  This gives me a big productivity boost.  Thanks!
