### ISSUE TITLE
`l` should not extend past last character of line

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#26]
`$` correctly places the normal cursor on the last character of the current line.

But currently, `l` (lowercase L) brings you to the character after the current line. `l` should not bring your cursor past the last character of the line.

**Comment by nosami** [comment]
Thank you for raising these issues :)

**Comment by nosami** [comment]
Fixed by https://github.com/nosami/XSVim/commit/0186aa57998c07eb3e3048d40ff5205d8fa7a8d0
