### ISSUE TITLE
latest release not working on mac

### ISSUE THREAD

**Issue by paolojulian** [nosami/XSVim#261]

**Comment by nosami** [comment]
Which version of XSVim are you using? Which version of VSMac?

**Comment by nosami** [comment]
Did you do this? https://github.com/nosami/XSVim#81-new-editor

**Comment by andywatts** [comment]
Same here.  

VSMac 8.2.2 (build 21)
XSVim 0.65.3
New editor disabled.

I tried wiping visual studio and it's ~/Library/Application Support...and reinstalled VS and XSVIM.
No luck...

Edit:  Tried install  XSVim v0.65.10.81 mpack.  no joy... 

Edit2:  Well, it's working great for .cs files, but not .txt.

**Comment by kwkhaw** [comment]
Same here, it doesn't work.
VSMac 8.2.2 (build 21)
XSVim 0.65.10.81.
Already disabled the checkbox as mentioned in https://github.com/nosami/XSVim#81-new-editor

Edit: Tried 2-3 times, uninstalled and reinstalled, restarted VS, doesn't work. Finally, for the last time, i restarted VS, it worked. :)

**Comment by nosami** [comment]
> Edit2: Well, it's working great for .cs files, but not .txt.

Yeah. That's because the new editor is now used for text & xml files :(

**Comment by nosami** [comment]
Maybe there is something I can fix/hack to force the old editor for now.. I'll look into it.

For now you can force the old editor manually using this context menu from the solution pad 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/667194/62777195-a9578980-baa4-11e9-9328-9ab02505c2c3.png">

**Comment by shawnbernard** [comment]
I followed the instructions and am using the old editor, but no vim key commands work in the editor. hjkl work in the Solutions menu, but nothing works in the editor window.

**Comment by nosami** [comment]
@shawnbernard which file types does it not work in? sounds like the addin is enabled but you are using the new editor

**Comment by nosami** [comment]
FWIW, it works for me in 8.2, 8.3 & 8.4

**Comment by altmnt** [comment]
Same issue. It shows blinking vim cursor but keys are not actually working. Solution pane navigation works using jwkl.

**Comment by nosami** [comment]
@altmnt - which file types? Are you sure you have disabled the new editor for C# file types?

**Comment by nosami** [comment]
I just installed everything from stable channel and then added XSVim 0.65.10.81 and everything works fine AFAICT

```
Visual Studio Enterprise 2019 for Mac
Version 8.2.4 (build 17)
Installation UUID: e521b709-ddc4-4b91-8863-f33e6f4c2e74
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

Mono Framework MDK
Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.2.0
	2.1.11
	2.1.10
	2.1.9
	2.1.8
	2.1.7
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.2.101
	2.1.700
	2.1.603
	2.1.505
	2.1.504
	2.1.503
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Mobile OpenJDK
Java SDK: /Users/jason/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Apple Developer Tools
Xcode 10.3 (14492.2)
Build 10G8

Xamarin.Mac
Version: 5.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

Xamarin Designer
Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

Build Information
Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2

Operating System
Mac OS X 10.15.0
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Jun 13 21:52:56 PDT 2019
    root:xnu-6110.0.0.121.5~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
Vim 0.65.10.81
```

**Comment by shawnbernard** [comment]
> I followed the instructions and am using the old editor, but no vim key commands work in the editor. hjkl work in the Solutions menu, but nothing works in the editor window.

So, I ended up rebooting (for a separate reason) and then everything worked fine.  ¯\_(ツ)_/¯

**Comment by altmnt** [comment]
Reboot did not really help for me. I am using old editor, VS 8.2.4 and XSVim 0.65.3 (from extension gallery).
Edit: Tried only on C# files

**Comment by nosami** [comment]
@altmnt please try 0.65.10.81 from the [releases page](https://github.com/nosami/XSVim/releases)

**Comment by altmnt** [comment]
> @altmnt please try 0.65.10.81 from the [releases page](https://github.com/nosami/XSVim/releases)

This one works :)

**Comment by paolojulian** [comment]
It already worked for me but i had to download manually the latest version. Weird

**Comment by nosami** [comment]
I just published 0.65.10.81 to the 8.2.4 feed (it was already published against 8.2 and 8.2.1, but silly that it needs republishing for each version of VSMac)

Thanks for reporting!

**Comment by netpoetica** [comment]
I'm using version 8.4 of VS for Mac and I don't see the "use old editor" option in my settings at all (I have verified I am looking in the same place as the supplied screenshot). Is there an alternative way to tell it to use the old editor? Thanks!

**Comment by nosami** [comment]
@netpoetica I think you will need to use VSVim. See my instructions here https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555

Let me know if it works for you - thanks!
