### ISSUE TITLE
command "gg=G" does not format document correctly.

### ISSUE THREAD

**Issue by faewin** [nosami/XSVim#263]
All text gets shifted to the left with no indentation.

![Image](https://i.imgur.com/NGgPfIB.png)

**Comment by nosami** [comment]
I have to admit that I only ever tried this feature with F# code.

I'll try and get it fixed. Thanks!

**Comment by nosami** [comment]
![formatdoc](https://user-images.githubusercontent.com/667194/65114099-74aceb00-d9dd-11e9-873f-89100972985c.gif)
Fixed in 0.65.11.81

**Comment by nosami** [comment]
@faewin you can get the mpack file from here https://github.com/nosami/XSVim/releases/download/0.65.11.81/XSVim.XSVim_0.65.11.81.mpack and install it via Visual Studio -> Extensions -> Install from file

**Comment by faewin** [comment]
@nosami Wow! That was fast. Thanks for the speedy fix! =)
