### ISSUE TITLE
VS for mac 8.3.4(build 8) not support XSVim

### ISSUE THREAD

**Issue by Tonvey** [nosami/XSVim#264]
I have updated my visual studio to 8.3.4 , then I reinstall xsvim (0.65.3) .  It dosn't work correctly  . Of course I have disabled "Open C# files in New Editor" feature , and choose the key bindings "Visual Studio + Vim" .   It appears that the Editor has load the addin and stay in Normal Mode, but It can't even  move the cursor when I pressed "HJKL"  . Every key is useless  .

**Comment by nosami** [comment]
Please could you share your log file just after this happened?

Help -> Open Log Directory -> Ide.log

If you are instead interested in a Vim addin for the new editor, I have been working on porting VsVim over to Mac - https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555

**Comment by Tonvey** [comment]
[Ide.log](https://github.com/nosami/XSVim/files/3739341/Ide.log)
Thanks for help  , here is the log file . I think I will try the new editor addin .

**Comment by nosami** [comment]
I don't plan on adding any new features to XSVim now that VsVim is working. VsVim is the future :)

I will try and keep XSVim working though for as long as I can.

Please could you try installing the addin from [here](https://github.com/nosami/XSVim/releases/download/0.65.11.81/XSVim.XSVim_0.65.11.81.mpack) if you want to try XSVim again. You are running a slightly older version.

**Comment by Tonvey** [comment]
It works ,thanks .

**Comment by nosami** [comment]
I just published 0.65.11.81 on the 8.3.4 feed. Thanks for reporting!
