### ISSUE TITLE
Can't do anything on vs for mac

### ISSUE THREAD

**Issue by iboss-ptk** [nosami/XSVim#265]
VS version 8.3.8 (community)
Vim version 0.65.3

I have already disable new editor and found out that when I open new file, I start in normal mode but I can't move via `hjkl` or arrows and when I press `i`, it also does not change to insert mode. Any clue? Thank you in advance :)

**Comment by nosami** [comment]
Yes. Please install this version https://github.com/nosami/XSVim/releases/download/0.65.11.81/XSVim.XSVim_0.65.11.81.mpack via `Visual Studio -> Extensions -> Install from file`

**Comment by nosami** [comment]
Alternatively, I have been working on making VsVim work on VSMac with the new editor. You can find instructions here https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555

**Comment by nosami** [comment]
I just published 0.65.11.81 on the VSMac 8.3.8 extension feed.

Thanks for reporting!

**Comment by donquixote1984** [comment]
> Yes. Please install this version https://github.com/nosami/XSVim/releases/download/0.65.11.81/XSVim.XSVim_0.65.11.81.mpack via `Visual Studio -> Extensions -> Install from file`

Nice. Love it. save my day
