### ISSUE TITLE
Not working inside .xaml files

### ISSUE THREAD

**Issue by organic-scholar** [nosami/XSVim#266]
This plugin is not enabled or not working in .xaml file editor

**Comment by nosami** [comment]
I believe your issue is that .xaml is using the new editor.

This extension only works for the older editor. You should probably try [these instructions to get VsVim running on VSMac](https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555)

**Comment by organic-scholar** [comment]
Yes, I also assumed so, going to try VsVim.

Thanks

**Comment by nosami** [comment]
@organic-scholar Let me know if you have any problems. Also I forgot to mention that [you need to use VSMac 8.4 for editing xaml files](https://github.com/VsVim/VsVim/pull/2733#issuecomment-541586899)

**Comment by organic-scholar** [comment]
I tried using VsVim with VSMac 8.3, it is working fine in c# files but in xaml files the behavior is buggy.
![2020-01-02 12 07 00](https://user-images.githubusercontent.com/4876549/71655445-90ec5200-2d58-11ea-9cae-517d92c8899b.gif)

**Comment by nosami** [comment]
It's a known issue. You need to be using VSMac 8.4 and the 8.4 branch of
VsVim for xaml support

**Comment by organic-scholar** [comment]
VSMac 8.4 is currently in the preview once it's there is a stable release I will give it a try.
Thanks.

**Comment by nosami** [comment]
Yeah. Sorry about that but it can't be helped. Fixes went into the editor in VSMac for 8.4 to fix this issue.
