### ISSUE TITLE
Clicking past end of line should not place normal cursor on the last character of that line

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#27]
Currently, if you click past the end of the line, the normal cursor will rest past the last character of the line.

And, thanks for knocking out all these issues quickly! I've been playing with Xamarin a bit, and really appreciate you adding vim support to it!

**Comment by nosami** [comment]
OK. Not sure whether or not it's possible to fix this but I'll give it a go.

Thanks for raising the issues :) I try and fix issues as fast as I can but I only have a small amount of time to work on this :)
