### ISSUE TITLE
df and dt commands delete one too few characters

### ISSUE THREAD

**Issue by dlprows** [nosami/XSVim#3]
If I have the following code

```
		public void SearchResultsCleared ()
		{
		}
```
with my cursor at the beginning of the first line and I do `dfv` it should delete "public v" and if i do `dtv` it should delete "public " (including the space after public) but instead it deletes "public " (with a space after public) and "public" (no space after public) respectively

**Comment by nosami** [comment]
Thanks, should be fixed now

**Comment by nosami** [comment]
There seems to be some issues with the build server right now. You can try the mpack file from here https://github.com/nosami/XSVim/releases/tag/0.13.1 and install manually
