### ISSUE TITLE
Some documents open with flipped cursor and replace mode

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#31]
Sometimes certain C# files open in VS7 with the cursor looking like the insert cursor. Hitting Escape does nothing.

Even though I see the insert cursor, I appear to be in normal mode. `hjkl` move around the document.

When I go into insert mode with `i`, it acts as if I had just hit `R`. In other words, instead of inserting text, I'm replacing the text under the cursor.

It doesn't do this for all C# files I open. I don't know why, though. But it's very consistent. If I close all tabs, and re-open the files, the same files will have the same problem.

**Comment by nosami** [comment]
I've seen this myself a few times but not sure how to reproduce. It's down to a change between XS and VS apis.

**Comment by nosami** [comment]
What I need to do as an interim step is clear state when a tab is closed, but not sure how yet.

**Comment by nosami** [comment]
To repro, change to insert mode, close the tab and reopen

**Comment by nosami** [comment]
It seems that there was a different bug that had the same effect. For reasons that I haven't investigated, Initialize() was called twice. This was causing the caret mode to be toggled twice (back  into insert mode)

Fixed in 0.16.9
