### ISSUE TITLE
'p' does not work properly in visual mode

### ISSUE THREAD

**Issue by nathanoconnor** [nosami/XSVim#37]
If I have yanked text and I attempt to paste it using the 'p' command after having selected text in visual mode, nothing happens.

**Comment by nosami** [comment]
I just tried this in vim. Starting with `abc` in normal mode, with the cursor on `a`, I type `vllyvllp`. The text wasn't pasted.

**Comment by nosami** [comment]
Oh, hang on... it overwrote the original `abc` with a new `abc`... I see now :)

**Comment by nosami** [comment]
Fixed in 0.16.10
