### ISSUE TITLE
'A' in normal mode puts the cursor in the wrong spot

### ISSUE THREAD

**Issue by dlprows** [nosami/XSVim#39]
'A' should put the cursor at the end of the line, but instead puts the cursor one character from the end of the line

**Comment by nosami** [comment]
Which version are you running? If you're not running 0.16.9, can you grab it from here? https://github.com/nosami/XSVim/releases

Thanks!

**Comment by nosami** [comment]
It's working in 0.16.9 / VS for Mac

**Comment by nosami** [comment]
Closing this, but if you have issues with 0.16.9, then please reopen. Thanks!

**Comment by dlprows** [comment]
It looks like its working. I believe i was on https://github.com/nosami/XSVim/releases/tag/0.16 which i had seen listed in the support for VS for mac issue.
Are you starting to keep the version listed in vs for mac extensions up to date, or should i look at the releases here on github for the latest?

**Comment by nosami** [comment]
As of yesterday, the latest version should be in the VS for Mac gallery, so you should just be able to rely on the VS for Mac updater for updates.
