### ISSUE TITLE
Release for VS 7.0

### ISSUE THREAD

**Issue by kamilgryniewicz** [nosami/XSVim#4]
Could you release a version for Visual Studio 7.0 please? 

I'm getting this: 
![screen shot 2017-03-17 at 15 37 48](https://cloud.githubusercontent.com/assets/2143223/24050917/504436d2-0b28-11e7-9511-f05ddae55e5f.png)
on the Preview 5 (7.0 build 1659) Visual Studio for Mac

Thanks!

**Comment by nosami** [comment]
Hi, you can try and install this version manually for now - https://github.com/nosami/XSVim/releases/download/untagged-debb1fa3660b34c946c5/XSVim.XSVim_0.13.mpack

Use Visual Studio -> Extensions -> Install from file

**Comment by kamilgryniewicz** [comment]
Unfortunately 404 on this link.

**Comment by vignesh-sankaran** [comment]
Unfortunately I still get the same error while trying to install it manually too

**Comment by nosami** [comment]
Sorry about that. Try this link https://github.com/nosami/XSVim/releases/download/0.13.1.1/XSVim.XSVim_0.13.mpack

**Comment by ashokgelal** [comment]
Compatibility issue is resolved with the latest version but now it comes with this:
 
![screenshot 2017-03-19 11 50 49](https://cloud.githubusercontent.com/assets/401055/24083325/8dd99cda-0c9a-11e7-8df3-5a6682c6678d.png)

**Comment by vignesh-sankaran** [comment]
Hmm it installs with the above dialog box, and it seems to be running but I don't have the Vim keyboard shortcuts in the code window still

**Comment by sowderca** [comment]
It appears that this may have been resolved with build 2715

**Comment by nosami** [comment]
Latest release for 7.0 https://github.com/nosami/XSVim/releases/tag/0.15

**Comment by nosami** [comment]
https://github.com/nosami/XSVim/releases/tag/0.16

**Comment by nosami** [comment]
Ok... I'm tired of updating this thread... but the latest version is always here https://github.com/nosami/XSVim/releases :)

**Comment by sowderca** [comment]
Thanks for your work on this. @nosami

**Comment by nosami** [comment]
0.18.0 is now available in the VS for Mac extension gallery.
