### ISSUE TITLE
Keys typed in insert mode should be repeatable with `.`

### ISSUE THREAD

**Issue by nosami** [nosami/XSVim#41]

**Comment by aguywithcode** [comment]
It looks like you have the . command implemented but it's repeating the last single command.
so if my last command is "h" (moveleft)  . repeats that.

but vim officially only stores the last **modifying** command. I.e. if I hit dd . it should delete two lines. If I hit 2dd. it should delete four.

Another example cwsometext followed by movement and then a . should repeat cwsometext at the new cursor location.

**Comment by nosami** [comment]
Yeah... I noticed this. Will get it fixed. Thanks for reporting!

**Comment by aguywithcode** [comment]
You sir are amazing. I wouldn't be able to use VS on Mac without this plugin. Do you take donations?

**Comment by nosami** [comment]
@mdizzy: No, but thanks :)
