### ISSUE TITLE
Add ex mode commands

### ISSUE THREAD

**Issue by nosami** [nosami/XSVim#42]
At least the simple ones for now

**Comment by decriptor** [comment]
some basic commands like:
`:w` -> save
`:wq` -> save and close tab
`:q` -> close file
`:q!` -> discard changes and close tab
`:e {file}` -> edit the file. Maybe have some kind of search/completion for classes?

others? https://www.fprintf.net/vimCheatSheet.html

**Comment by nosami** [comment]
Might be able to use this code from VsVim https://github.com/jaredpar/VsVim/blob/447d980da9aa6c761238e39df9d2b64424643de1/Src/VimCore/Interpreter_Parser.fs

to parse commands. It looks quite portable.

**Comment by nosami** [comment]
Added some makeshift code for `q, q!, qa, qa!, w, wq, wq!, wa, wa!`

**Comment by nosami** [comment]
https://github.com/nosami/XSVim/commit/fdec866ad31ec4eb55071e7a682070a0f190a9aa adds command substitute mode `:%s/find/replace` and `:'<,'>s/find/replace`

**Comment by nosami** [comment]
Closing as VsVim supports this

https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555
