### ISSUE TITLE
Treatment of quoted blocks is not the same as in VIM

### ISSUE THREAD

**Issue by shirshov** [nosami/XSVim#51]
Quoted blocks are special in VIM, and currently XSVim treats them incorrectly.
For example, when executing `ci"` on this:
```
a "b"
[c] "d" 
```
The result in VIM is 
```
a "b"
c "|"
```

whereas in XSVim it is

```
a ""b|d""
```

Comments: 

Actually, I can't find a definite reference for this. But VIM's model makes sense to me. Quoted strings are rarely nested, and in programming languages we usually deal with lines like these:
```
var foo = "abc";
var bar = "def";
```

If the cursor is _anywhere_  on the second line (except the semicolon), and I type `ci"ghi`  I expect to see
```
var foo = "abc";
var bar = "ghi";
```

Super convenient.

**Comment by nosami** [comment]
Yep... I'll get this fixed!
