### ISSUE TITLE
Ability to map jj to esc

### ISSUE THREAD

**Issue by joe-zhang3** [nosami/XSVim#56]
I've been using it for long time with other IDE's (Like visual studio code) by adding some map configurations. 

It will be even better if the default .vimrc file can be read and respect.

**Comment by nosami** [comment]
Yeah, I'd like to add this at some point but it's not high on my priority list. 

In Vim, when you use an insert mapping like this, it needs to pause for some time after hitting the first `j` to see if you are going to press the 2nd one :)

**Comment by nosami** [comment]
Fixed in 0.44.0 by https://github.com/nosami/XSVim/pull/172
