### ISSUE TITLE
Fix "^" motion

### ISSUE THREAD

**Issue by kibiz0r** [nosami/XSVim#6]
Right now, ^ behaves the same way as 0, which is not the standard vim behavior. My muscle memory would be very thankful if it worked like this:

> ^
> To the first non-blank character of the line. |exclusive| motion.

http://wwwcdf.pd.infn.it/vim/motion.html#left-right-motions

**Comment by nosami** [comment]
Ah, you are right. I always use _ for this. Will fix!
