### ISSUE TITLE
`F`, `f`, `T`, and `t` commands fail for numerical arguments except for 0

### ISSUE THREAD

**Issue by tdfacer** [nosami/XSVim#63]
For example, if you had "abc$ d1 d2 d3 d4" and pressed `f4` the cursor wouldn't move.  However, with the same  text, if you press `f4d` it would result in this: "abc d1 d2 d3 d$4".  This makes me think it is being treated as a quantifier and we may just need to change a `run` to a `runOnce` somewhere.

**Comment by nosami** [comment]
ah, I see. There was a similar bug with `r4` that was fixed [here](https://github.com/nosami/XSVim/blob/eb084f1cbb8af26a939f2ed887bf1ef36e3734a9/XSVim/XSVim.fs#L688)

**Comment by nosami** [comment]
I think we need similar rules for `F`, `f`, `T` and `t` in between these lines https://github.com/nosami/XSVim/blob/eb084f1cbb8af26a939f2ed887bf1ef36e3734a9/XSVim/XSVim.fs#L696-L698

Can probably match all 4 of these chars by using [FindChar](https://github.com/nosami/XSVim/blob/eb084f1cbb8af26a939f2ed887bf1ef36e3734a9/XSVim/XSVim.fs#L657-L661)

**Comment by nosami** [comment]
I haven't tried this yet, but does `2fg` work for example to find the 2nd `g` on the line? If not, I think it can be fixed by moving your `FindChar` pattern match down a few lines.
