### ISSUE TITLE
Support marks

### ISSUE THREAD

**Issue by nosami** [nosami/XSVim#68]

**Comment by nosami** [comment]
`'a` is like \`a but jumps to the first character on the line where mark `a` is

**Comment by nosami** [comment]
This is pretty much done now... ` and ' both work. Just need to differentiate between editor marks and global marks (lowercase vs uppercase mark names)

**Comment by mweber26** [comment]
You mention this is done but **ma** and **mb** then **:'a'bd** says "could not parse".  Are just marks there and they cannot be used in expressions yet? For example **:1,3d** says could not parse also.

**Comment by nosami** [comment]
No ex mode (`:`) support for marks yet. Most ex mode commands don't work at the moment.

**Comment by nosami** [comment]
@mweber26: Having said that, if it's something that you use frequently, then I can prioritise that.

**Comment by mweber26** [comment]
Yeah - of the commands I am used to using, ex commands seem to be missing, and I have run into #117 a few times as well.

I use **'a,'bd** and **p** to move code around fairly regularly.

**Comment by nosami** [comment]
I have a [branch where I was working](https://github.com/nosami/XSVim/tree/textchanges) on #117 . I didn't quite get it working though. I'll try and get that working next.

**Comment by nosami** [comment]
#117 was fixed by #220

**Comment by nosami** [comment]
`d'a` and `v'a` etc should work too.

**Comment by nosami** [comment]
@mweber26  d'a, v'a and :'a,'bd are all now working in 0.58.0

**Comment by mweber26** [comment]
Works great!  Thanks
