### ISSUE TITLE
"Escape" should not move cursor left if already in normal mode.

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#7]
When going from insert mode to normal mode, the cursor has to move left. However, this Move command also runs if you're already in normal mode, which means if you're a compulsive Escaper it will keep moving your cursor left, which is unexpected.

I think usually vim will even cause a system sound if you hit Escape while in Normal Mode, to let you know you've escaped out of everything you possibly could?

**Comment by nosami** [comment]
Thanks for reporting. I've been a little busy with work recently - sorry for the delay.
