### ISSUE TITLE
Implement `'.` to jump to last edit location

### ISSUE THREAD

**Issue by shirshov** [nosami/XSVim#72]
`'.` should return to the last edited line.

It looks like it's a specific case of a more general feature: marks. Dot is a mark for the last edited line.

**Comment by nosami** [comment]
```
`.
```
 There is a backtick variant that should do the same thing.

**Comment by nosami** [comment]
So, the backtick variant isn't quite the same. `. goes to the end of the last edit

**Comment by nosami** [comment]
`'.` will go to the start of the line of wherever the backtick variant is. The same for all other marks too.
