### ISSUE TITLE
"$" should not bring you to the last character in the line, not one past it

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#8]
Say you're in the line:

`abc;`

If you hit `$`in normal mode, the block cursor should land on `;`, not the space after `;`.

**Comment by nosami** [comment]
Which version of XSVim / XS / VS for Mac are you using?

This works for me with XSVim 0.16 / VS for Mac

**Comment by richkzad** [comment]
Ah, this was 0.13 with XS! I will try 0.16 with the VS for Mac Preview.

**Comment by nosami** [comment]
Thanks! It's not in the feed yet, so you'll need to install it from here https://github.com/nosami/XSVim/releases/tag/0.16

**Comment by richkzad** [comment]
Okay, `$` works!

But found another somewhat related problem:

If you move up/down to a line which doesn't have enough characters to keep your cursor position, the cursor will land on the space after the last character of the line.

Example, (where `#` is the cursor)

```
Testi#g
Hi.
```
(Tap `j`)
```
Testing
Hi.#
```

**Comment by nosami** [comment]
Ok... thanks - I'll fix that.

**Comment by nosami** [comment]
Fixed by https://github.com/nosami/XSVim/commit/ea27f4def76ccbfb236de82754548f2d84270c48
