### ISSUE TITLE
W, B, E support

### ISSUE THREAD

**Issue by richkzad** [nosami/XSVim#9]
The uppercase `W`, `B`, `E` commands currently do nothing (or work unexpectedly.)

They should be like `w`, `b` and `e` except treating words as delimited by whitespace, not other characters like `(` and `.` (so, they tend to move further in code.)

See `word` vs `WORD` here: http://vimdoc.sourceforge.net/htmldoc/motion.html#WORD

**Comment by nosami** [comment]
Added to 0.20.0. Please let me know if they work as you expect - I don't use these myself... maybe I will now :)
