### ISSUE TITLE
`e` Jumps Over Some Punctuation Incorrectly

### ISSUE THREAD

**Issue by tdfacer** [nosami/XSVim#95]
* Vim behaves like this:
|         "int model$);\n " `e` "int model);$\n "
* XSVim behaves like this:
|         "int model$);\n " `e` "int model);\n $"

* Note the error in jumping past the last char and over the new lines one command early
* I also noticed it in this scenario:
|         "Task<List<SomeWord$>> nextWord" `e` "Task<List<SomeWord$>> nextWord$"
|         when it should move to here; "Task<List<SomeWord>>$ nextWord"

**Comment by nosami** [comment]
OK. Will get this fixed

**Comment by nosami** [comment]
This is what the vim docs have to say about it

```
                                                        *word*
A word consists of a sequence of letters, digits and underscores, or a
sequence of other non-blank characters, separated with white space (spaces,
tabs, <EOL>).  This can be changed with the 'iskeyword' option.  An empty line
is also considered to be a word.
                                                        *WORD*
A WORD consists of a sequence of non-blank characters, separated with white
space.  An empty line is also considered to be a WORD.
```

`set iskeyword?` yields  `iskeyword=!-~,^*,^|,^",192-255`
